
    create table Pregunta_posiblesRespuestas (
        Pregunta_id bigint not null,
        posiblesRespuestas varchar(255)
    )

    create table Preguntas (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        encuesta varchar(255),
        primary key (id)
    )

    create table Refugio (
        id bigint generated by default as identity (start with 1),
        capacidad integer not null,
        direccion varchar(255),
        lugares_disponibles integer not null,
        nombre varchar(255),
        patio boolean,
        telefono varchar(255),
        primary key (id)
    )

    create table Respuestas (
        id bigint generated by default as identity (start with 1),
        respuesta varchar(255),
        pregunta_id bigint,
        primary key (id)
    )

    alter table Pregunta_posiblesRespuestas 
        add constraint FK_2myedpiiw4mlc2fljb9ymd7a1 
        foreign key (Pregunta_id) 
        references Preguntas

    alter table Respuestas 
        add constraint FK_6bm10mqfcrp4n5e7wel4xo06l 
        foreign key (pregunta_id) 
        references Preguntas
