
    create table Asociaciones (
        id bigint generated by default as identity (start with 1),
        coordenadaX varchar(255),
        coordenadaY varchar(255),
        direccion varchar(255),
        primary key (id)
    )

    create table Chapita (
        id bigint generated by default as identity (start with 1),
        owner_id bigint,
        primary key (id)
    )

    create table DuenioMascota (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        contacto_apellido varchar(255),
        mail varchar(255),
        contacto_nombre varchar(255),
        telefono varchar(255),
        document_id bigint,
        tipo varchar(255),
        fechaNacimiento varbinary(255),
        nombre varchar(255),
        password varchar(255),
        usuario varchar(255),
        primary key (id)
    )

    create table Mascota (
        id bigint generated by default as identity (start with 1),
        apodo varchar(255),
        descripcionFisica varchar(255),
        edad integer not null,
        nombre varchar(255),
        sexo varchar(255),
        tipoMascota varchar(255),
        chapita_id bigint,
        mascota_id bigint,
        primary key (id)
    )

    create table MascotaEncontrada (
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        fecha varbinary(255),
        coordenadaX varchar(255),
        coordenadaY varchar(255),
        tamanio varchar(255),
        tipoMascota varchar(255),
        chapita_id bigint,
        primary key (id)
    )

    create table MascotaEncontrada_caracteristicas (
        MascotaEncontrada_id bigint not null,
        valor varchar(255)
    )

    create table MascotaEncontrada_foto (
        MascotaEncontrada_id bigint not null,
        foto varchar(255)
    )

    create table Mascota_caracteristicas (
        Mascota_id bigint not null,
        valor varchar(255)
    )

    create table Mascota_fotos (
        Mascota_id bigint not null,
        fotos varchar(255)
    )

    create table Pregunta_posiblesRespuestas (
        Pregunta_id bigint not null,
        posiblesRespuestas varchar(255)
    )

    create table Preguntas (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        encuesta varchar(255),
        pregunta_id bigint,
        primary key (id)
    )

    create table Refugios (
        id bigint generated by default as identity (start with 1),
        direccion varchar(255),
        nombre varchar(255),
        telefono varchar(255),
        primary key (id)
    )

    create table Rescate (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        contacto_apellido varchar(255),
        mail varchar(255),
        contacto_nombre varchar(255),
        telefono varchar(255),
        document_id bigint,
        tipo varchar(255),
        fechaNacimiento varbinary(255),
        nombre varchar(255),
        domicilioRescatista varchar(255),
        rescatistaAlbergaMascota boolean,
        mascota_id bigint,
        refugio_id bigint,
        primary key (id)
    )

    create table Respuestas (
        id bigint generated by default as identity (start with 1),
        respuesta varchar(255),
        pregunta_id bigint,
        primary key (id)
    )

    create table Voluntario (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        contacto_apellido varchar(255),
        mail varchar(255),
        contacto_nombre varchar(255),
        telefono varchar(255),
        document_id bigint,
        tipo varchar(255),
        fechaNacimiento varbinary(255),
        nombre varchar(255),
        password varchar(255),
        usuario varchar(255),
        asociacion_id bigint,
        primary key (id)
    )

    alter table Chapita 
        add constraint FK_hptyghiw3tmox2pd3phfc09a8 
        foreign key (owner_id) 
        references DuenioMascota

    alter table Mascota 
        add constraint FK_fd5yx0y0l9ypgclkd0db7d1dx 
        foreign key (chapita_id) 
        references Chapita

    alter table Mascota 
        add constraint FK_re5vmqdgmn229ghjcs8qyqfen 
        foreign key (mascota_id) 
        references DuenioMascota

    alter table MascotaEncontrada 
        add constraint FK_7m9ptscd5r3vjbp7k9t2tivqc 
        foreign key (chapita_id) 
        references Chapita

    alter table MascotaEncontrada_caracteristicas 
        add constraint FK_5e135o10icnhdejtix4h7giq7 
        foreign key (MascotaEncontrada_id) 
        references MascotaEncontrada

    alter table MascotaEncontrada_foto 
        add constraint FK_o52hm44cg4ttxrf16vonq3cte 
        foreign key (MascotaEncontrada_id) 
        references MascotaEncontrada

    alter table Mascota_caracteristicas 
        add constraint FK_py5tsq0b4bjbjsisej94uie3n 
        foreign key (Mascota_id) 
        references Mascota

    alter table Mascota_fotos 
        add constraint FK_dclevnore3slbildn3hia9nlo 
        foreign key (Mascota_id) 
        references Mascota

    alter table Pregunta_posiblesRespuestas 
        add constraint FK_2myedpiiw4mlc2fljb9ymd7a1 
        foreign key (Pregunta_id) 
        references Preguntas

    alter table Preguntas 
        add constraint FK_598iop8xejo4bx4ek7u95f6dw 
        foreign key (pregunta_id) 
        references Asociaciones

    alter table Rescate 
        add constraint FK_8as215usm6q9mm4vqmsfha1qe 
        foreign key (mascota_id) 
        references MascotaEncontrada

    alter table Rescate 
        add constraint FK_r98lyin5qxgjiwjojug9x8teb 
        foreign key (refugio_id) 
        references Refugios

    alter table Respuestas 
        add constraint FK_6bm10mqfcrp4n5e7wel4xo06l 
        foreign key (pregunta_id) 
        references Preguntas

    alter table Voluntario 
        add constraint FK_15jg7c6d6l9uuqpibrvatuw9d 
        foreign key (asociacion_id) 
        references Asociaciones
